[package]
name = "iwe"
description = "IWE CLI utility"
include = ["Cargo.toml", "src/**/*.rs", "src/**/*.yaml", "tests/**/*.rs", "tests/**/*.md", "templates/**/*", "help/**/*", "docs/**/*"]
autotests = false
autobenches = false

version.workspace = true
repository.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "iwe"
path = "src/main.rs"

[dependencies]
liwe.workspace = true
diwe.workspace = true
indoc.workspace = true
clap.workspace = true
clap_complete.workspace = true
clap_complete_nushell.workspace = true
itertools.workspace = true
log.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
toml_edit.workspace = true
regex.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
graphviz-rust.workspace = true
minijinja.workspace = true
csv.workspace = true
chrono.workspace = true
sys-locale.workspace = true
serde_yaml.workspace = true
sanitize-filename.workspace = true

[[test]]
name = "integration"
path = "tests/main.rs"

[[bench]]
name = "load"
harness = false

[[bench]]
name = "query"
harness = false

[[bench]]
name = "similarity"
harness = false

[dev-dependencies]
pretty_assertions.workspace = true
jsonschema.workspace = true
tempfile.workspace = true
uuid.workspace = true
criterion = { version = "0.7", features = ["html_reports"] }
